### ISSUE TITLE
Функция calc_me без второго параметра возвращает неверный результат

### ISSUE THREAD

**Issue by Albinaqa** [alex-pancho/module14#2]
Вызвать функцию calc_me с параметрами: calc_me(4, None,"+")
Ожидаемый результат: «ERROR: send me Number2»
Фактический результат: «ERROR: send me Number1»
Приоритет: низкий
Важность: низкая
Версия: 0.4

**Comment by alex-pancho** [comment]
сюда баги не пишите, пишите в свой гит )
